paths:
  /tracks/{track_id}:
    get:
      summary: Позволяет получить информацию о треке включая метаданные
      tags: 
        - Tracks
      parameters:
        - name: track_id
          in: path
          required: true
          description: Уникальный индетификатор трека
          schema:
            type: string
      responses:
        200:
          description: Успешный запрос
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponseSuccess'
                  - type: object
                    properties: 
                      message:
                        example: 'Track fetched'
                      data: 
                        $ref: '#/components/schemas/TrackData'
        400:
          description: |
            Ошибка валидации или некорректный запрос.
            Возможные error.code:
              - VALIDATION_ERROR
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/BadRequestErrorResponse'
                  - $ref: '#/components/schemas/ValidationErrorResponse'
        404:
          description: |
            Сущность не найдена в базе данных.
            Возможные error.code:
              - TRACK_DOES_NOT_EXISTS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'
        500:
          description: |
            Непредвиденная ошибка во время обработки запроса.
            Возможные error.code:
              - TRACK_FETCH_ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
